ROBOT:
                state:
                        type: joint_state_controller/JointStateController
                        publish_rate: 50
                position:
                        steer_joint_1:
                                type: position_controllers/JointPositionController
                                joint: steer_joint_1
                                pid: {p: 10.0, i: 1.0, d: 200.0}
                        steer_joint_2:
                                type: position_controllers/JointPositionController
                                joint: steer_joint_2
                                pid: {p: 10.0, i: 1.0, d: 200.0}
                        steer_joint_3:
                                type: position_controllers/JointPositionController
                                joint: steer_joint_3
                                pid: {p: 10.0, i: 1.0, d: 200.0}
                        steer_joint_4:
                                type: position_controllers/JointPositionController
                                joint: steer_joint_4
                                pid: {p: 10.0, i: 1.0, d: 200.0}                                                                        
                velocity:
                        wheel_joint_1:
                                type: velocity_controllers/JointVelocityController
                                joint: wheel_joint_1
                                pid: {p: 10.0, i: 1.0, d: 200.0}
                        wheel_joint_2:
                                type: velocity_controllers/JointVelocityController
                                joint: wheel_joint_2
                                pid: {p: 10.0, i: 1.0, d: 200.0}
                        wheel_joint_3:
                                type: velocity_controllers/JointVelocityController
                                joint: wheel_joint_3
                                pid: {p: 10.0, i: 1.0, d: 200.0}
                        wheel_joint_4:
                                type: velocity_controllers/JointVelocityController
                                joint: wheel_joint_4
                                pid: {p: 10.0, i: 1.0, d: 200.0}                                                                                                
