grisho:
                state:
                        type: joint_state_controller/JointStateController
                        publish_rate: 50
                position:
                        chassis_wheel_left_joint:
                                type: effort_controllers/JointPositionController
                                joint: chassis_wheel_left_joint
                                pid: {p: 10.0, i: 1.0, d: 1.0}
                        chassis_wheel_right_joint:
                                type: effort_controllers/JointPositionController
                                joint: chassis_wheel_right_joint
                                pid: {p: 10.0, i: 1.0, d: 1.0}
                        base_to_rot_fork:
                                type: effort_controllers/JointPositionController
                                joint: base_to_rot_fork
                                pid: {p: 10.0, i: 1.0, d: 1.0}
                        fork_to_wheel:
                                type: effort_controllers/JointVelocityController
                                joint: fork_to_wheel
                                pid: {p: 1000.0, i: 100.0, d: 1.0}

