controller_joint_names: ['', 'base_to_input_rot_joint', 'input_shat_to_fork_joint', 'input_translation_to_base', 'input_translation_to_translation_vertical_shaft_bevel_joint', 'horiz_bevel_to_wheel_joint', ]
